/*
                               Thought Note


Through this component I tried to provides a simple search functionality for a product 
catalog.

Here I Imported  the necessary dependencies and components.

I also Defined the functional component SearchPage.


I used  the useNavigate hook from React Router to get access to the
navigate function, which is used to navigate to different pages 
in the application.


I Defined the allproducts state variable, which holds an array of 
all the products retrieved from the API.


I Defined the GetAllProducts function, which retrieves all the products
from the API using Axios and updates the allproducts state variable.

Calls the GetAllProducts function when the component mounts using the
useEffect hook.


I Defined the searchHandle function, which sends a search request to the 
API when the user types a search query in the search box and updates 
the allproducts state variable with the search results.


Renders a search box and a list of search results using the SearchResultCard component. 


The list of search results is generated by mapping over the allproducts state variable 
and passing each product to the SearchResultCard component.                             

*/
import SearchResultCard from "../cards/searchresultcard";
import React, { useEffect, useState } from "react";

import axios from "axios";
import Swal from "sweetalert2";
import { API_BASE_URL } from "../config";
import { useNavigate } from "react-router-dom";
function SearchPage() {
  //defining usenavigate
  const navigate = useNavigate();
  //search API // By default have all products
  const [allproducts, setAllProducts] = useState([]);
  const GetAllProducts = async () => {
    const response = await axios.get(`${API_BASE_URL}/allproduct`);
    //debugger;
    if (response.status === 200) {
      setAllProducts(response.data.posts);
    } else {
      Swal.fire({
        icon: "error",
        title: "Some error occured",
      });
    }
  };
  useEffect(() => {
    GetAllProducts();
  }, []);
  //Connecting the search API
  const searchHandle = async (event) => {
    // console.warn(event.target.value);
    let key = event.target.value;
    let result = await fetch(`${API_BASE_URL}/search/${key}`);
    result = await result.json();
    if (result) {
      navigate("/searchpage");
      setAllProducts(result);
    }
    /*else {
      navigate("/home");
    }*/
  };
  return (
    <div className="container shadow-lg">
      <br></br>
      <div className="row">
        <div className="col-2">
          <button className="form-control btn btn-primary">
            <i className="fa-solid fa-magnifying-glass"></i>
          </button>
        </div>
        <div className="col-10">
          <input
            style={{ border: "1px solid black" }}
            onChange={searchHandle}
            type="text"
            className="form-control"
            placeholder="Search Product here"
            aria-label="Recipient's username"
            aria-describedby="button-addon2"
          />
        </div>
      </div>

      <br></br>
      {allproducts
        .map((product) => {
          return (
            <div
              className="col-md-12  col-sm-12 mb-sm-2"
              id="productspace"
              key={product._id}
            >
              {" "}
              <SearchResultCard
                productData={product}
                GetAllProducts={GetAllProducts}
              />{" "}
            </div>
          );
        })
        .reverse()}
    </div>
  );
}
export default SearchPage;
